MainPage + Search
VsALT2000/template pull request #1
Opened 2022-03-03 07:14 UTC by VsALT2000

2022-03-04 12:43 UTC, alserz1 requested changes

2022-03-04 12:43 UTC, alserz1 commented on package.json
> +    "redux-thunk": "^2.4.1",
знание технологий это хорошо, но для подключения каждой зависимости должна быть причина. На данный момент я вижу следующее:
1) redux (и всё, что с ним связано) не используется. Есть немного логики, но она сводится к тому, что в App прокидываются несколько массивов из родителя.
2) classnames используется, чтобы склеить две строки.

Я не против сторонних библиотек, просто нужно подключать их по мере необходимости. Крайне редко стоит подключать что-то "на будущее", потому что это не бесплатно. Вся команда должна научиться пользоваться новой технологией, пользователь будет получать больше кода, а выигрыша может и не быть.

Также, есть другая причина по которой я пишу всё это – написание своего собственного кода для решения проблем, которые решают библиотеки, помогает разобраться как они работают. А это всегда очень полезные знания, потому что когда-нибудь возникнет необходимость отлаживать библиотечный код)

2022-03-04 12:43 UTC, alserz1 commented on src/App.module.css
> +main {
не стоит писать селекторы по типу элемента без крайней необходимости (например, при нормализации CSS их можно использовать). `main` достаточно безопасен, потому что он должен быть один на странице, но тот же `input` - нет. Полей ввода может быть много, они могут иметь разные цели, соответственно, выглядеть они будут тоже по-разному.

Если хочется, чтобы элемент имел какие-то конкретные стили на всех страницах, то лучше сделать из него компонент, сделать для него отдельный CSS-файл, и там прописать класс с нужными свойствами.

2022-03-04 12:43 UTC, alserz1 commented on src/components/MainPage/MainPage.tsx
> +    const time = Intl.DateTimeFormat("ru", {hour: 'numeric'}).format(new Date());
зачем так сложно? new Date().getHours() сразу даст цифру от 0 до 23. Заодно все if'ы можно упростить будет)

И здесь не сильно критично, но я бы вычисление этой фразы вынес в отдельную функцию, и в каждом if написал return. Это даст следующие плюсы:
1) Компонент будет чуть легче читаться.
2) Можно будет в каждой ветке if написать return, это и читать проще, и браузер лишние условия не проверяет.
3) Никто не сможет изменить nameTime, даже случайно. Потому что либо этой переменной не будет, либо её можно будет объявить через const.

2022-03-04 12:43 UTC, alserz1 commented on src/components/common/Tile/LongTile.tsx
> +                <img className={classes.image} src={props.link} alt={"Обложка"}/>
лучше указывать атрибуты width и height у картинок. В противном случае браузер заранее не знает сколько места ему нужно зарезервировать под картинку, и может произойти сдвиг контента

2022-03-04 12:43 UTC, alserz1 commented on src/components/common/Tile/SquareTile.module.css
> +    border-radius: 10px;
border-radius: 10px это явно что-то общее у всех типов плитки. И у них уже есть общий класс tile-container, почему это не находится там?

А ещё цвета в SquareTile совпадают с цветами в LongTile, лучше вынести такие цвета в переменные. Да и 10px совпадают, тоже можно объединить

2022-03-04 12:43 UTC, alserz1 commented on src/components/common/Tile/SquareTile.module.css
> +.tile_container::after {
зачем здесь border и overflow?

2022-03-04 12:43 UTC, alserz1 commented on src/components/common/Tile/LongTile.module.css
> +.podcast {
Вся эта пачка классов не используется в LongTile

2022-03-04 12:43 UTC, alserz1 commented on src/components/common/Tile/SquareTile.tsx
> +    switch (props.type) {
опять же, я бы сделал отдельную функцию и в каждой ветке просто написал return. И если весь список типов заранее известен и все названия совпадают с классами, то можно вообще написать `classes[props.type]`. Тут случай по умолчанию все равно не обрабатывается, т.е. на непредусмотренных кейсах сломаются оба варианта)

2022-03-04 12:45 UTC, alserz1 commented on .idea/modules.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Лучше сразу всю папку .idea в .gitignore закидывать

2022-03-04 12:54 UTC, VsALT2000 commented on package.json
> +    "redux-thunk": "^2.4.1",
Я не первый раз пишу проекты на реакте, и уже некоторые устоявшиеся привычки у меня появились. Удобно прописывать классы через cn, особенно когда будут более сложные варианты с ветвлением. Redux вообще основа будущего приложения. Насколько я понял, этот же проект пойдёт и на финальный проект с API Spotify, а следовательно управление BLL необходимо и чем раньше его начать прописывать, тем меньше компонент придётся переделывать в дальнейшем.

2022-03-04 12:56 UTC, VsALT2000 commented on src/App.module.css
> +main {
Ой, только сейчас заметил, что в задании просят "Минимально используются селекторы по типу элемента и "*" ". Невнимательно прочитал, сначала подумал что просят наоборот использовать их по максимуму. Но это дело поправимое.

2022-03-04 13:01 UTC, VsALT2000 commented on src/components/common/Tile/LongTile.tsx
> +                <img className={classes.image} src={props.link} alt={"Обложка"}/>
Но если есть одноимённые свойства в css? Разве они имеют отличия в устройстве?

2022-03-04 13:09 UTC, VsALT2000 commented on src/components/common/Tile/SquareTile.module.css
> +    border-radius: 10px;
Вот тут сам не знаю, какой-то баг, мб стоило побольше покопаться и поискать, в чём причина, но когда прописывал это свойство в tile-container, оно просто не применялось, хотя цвет менялся в зависимости от типа.

2022-03-04 13:10 UTC, VsALT2000 commented on src/components/common/Tile/SquareTile.module.css
> +.tile_container::after {
Не подтёр лишнее)

2022-03-04 13:28 UTC, merged

2022-03-05 05:31 UTC, alserz1 commented on package.json
> +    "redux-thunk": "^2.4.1",
Ещё раз повторюсь, не стоит подключать что-то заранее, потому что оно может вообще не понадобиться. Не просто так существует куча статей в духе "you might not need redux", и даже отдельный раздел в документации. Сейчас он просто не используется, т.е. количество переписывания будет ровно тем же самым.

Сейчас ты этим показываешь скорее недостаток опыта и некоторое забивание на пользователей. Все продукты делаются для пользователей, а пользователей никогда не волнует какие библиотеки ты используешь. Но они вполне себе могут заметить, что сайт работает медленно из-за пачки лишнего кода.

2022-03-05 05:35 UTC, alserz1 commented on src/components/common/Tile/LongTile.tsx
> +                <img className={classes.image} src={props.link} alt={"Обложка"}/>
Чтобы браузер выцепил эти свойства из CSS ему нужно загрузить файл, распарсить его, построить CSSOM и применить его. Пока он этого не сделает - он не знает сколько места нужно отводить под картинку, т.е. это может потенциально привести к скачкам контента.

2022-03-05 05:36 UTC, alserz1 commented on src/components/common/Tile/SquareTile.module.css
> +    border-radius: 10px;
Время на сдачу ещё есть, покопайся

2022-03-05 05:39 UTC, alserz1 commented
На будущее, не надо мержить пока не разберёмся со всеми замечаниями. Скакать по разным PR очень неудобно, невозможно удержать в голове все вещи по которым я писал.